exp_name: "llama3_whisper_s_cont_librispeech_960"

# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Meta-Llama-3-8B-Instruct"
audio_model: "openai/whisper-small"


max_steps: 8788  # 281241 / 4 / 8, 1 epoch

data_sets: []

device: "cuda"

batch_size: 4

report_logs_to: ["tensorboard", "wandb"]

data_dicts:
  - path: "fixie-ai/librispeech_asr"
    name: "clean"
    splits:
      - "train.100"
      - "train.360"
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"
  - path: "fixie-ai/librispeech_asr"
    name: "other"
    splits:
      - "train.500"
    user_template: "Continue the following text using less than 50 words:\n\n<|audio|>"
    assistant_template: "{{ continuation }}"
    transcript_template: "{{ text }}"