
exp_name: "ultravox-streaming-experiments-1s"
# Make sure to accept the license agreement on huggingface hub
text_model: "meta-llama/Llama-3.2-1B-Instruct"
audio_model: "openai/whisper-small"
loss_config:
  # Choose from ["KL_Divergence", "CrossEntropy"], default is "KL_Divergence"
  loss_function: "KL_Divergence"
train_sets:
  - name: librispeech-clean-continuation
  - name: librispeech-other-continuation
  - name: peoplespeech-clean-continuation
    weight: 4
  - name: commonvoice-en-continuation
    weight: 4
  - name: librispeech-clean-transcription
    weight: 4
  - name: librispeech-other-transcription
  - name: peoplespeech-clean-transcription
  - name: commonvoice-en-transcription
# Temporarily remove heysquad_human from val_sets as it causes the training to fail.
val_sets:
  - name: peoplespeech
batch_size: 24
max_steps: 10000 # x8x24 = 2,764,800
audio_latency_block_size: 100 # null for non-causal, 100 for 1s, 200 for 2s, and so on.