# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [main, prod]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [main, prod]
    paths-ignore:
      - "docs/**"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: us-central1-docker.pkg.dev/fixie-frame/ultravox-training/ultravox-training:v2

    # permissions:
    #   # Gives the action the necessary permissions for publishing new
    #   # comments in pull requests.
    #   pull-requests: write
    #   # Gives the action the necessary permissions for pushing data to the
    #   # python-coverage-comment-action branch, and for editing existing
    #   # comments (to avoid publishing multiple comments in the same PR)
    #   contents: write

    steps:
      - name: Install git-lfs
        run: |
          apt-get update && apt-get install -y git-lfs
          
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: extractions/setup-just@v1

      # - name: Set up Python 3.11
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.11

      - name: Install dependencies
        run: |
          . $VENV_PATH/bin/activate
          just install
          just install-augs-system

      - name: Run checks
        run: |
          . $VENV_PATH/bin/activate
          just check

      - name: Run tests and coverage
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          . $VENV_PATH/bin/activate
          just test-verbose

      # - name: Coverage comment
      #   id: coverage_comment
      #   uses: py-cov-action/python-coverage-comment-action@v3
      #   with:
      #     GITHUB_TOKEN: ${{ github.token }}
      #     COVERAGE_PATH: ultravox
